### ISSUE TITLE
Make navbar collapse

### ISSUE THREAD

**Issue by JSAssassin** [eden-learning/eden-client#37]
As a user, I want the navbar to collapse on mobile when I click on a nav-item

**Comment by andreamartz** [comment]
The following info comes from conversations with Tashi:

The function to collapse the navbar needs to be part of (i.e., inside) the Navbar.js component, and it should be called using the onClick event for React.  Both of these are changes that require a refactoring of the current code.

To achieve the same functionality that we have with the current code, we could attach the DOM event to the ComponentDidMount lifecycle method.  To use the lifecycle component, change the component from a function to a class

```
componentDidMount() {
   document.addEventListener('click', this.collapseMobileNav);
} 
```

We also need to unregister the event to remove the event listener when the navbar is removed from the screen:

```
componentWillUnmount() {
    document.removeEventListener('click', this.collapseMobileNav);
} 
```
